import { Inter } from 'next/font/google'
import cl from 'classnames'
import '@/styles/normalize.css'
import '@/styles/global.css'
import s from './styles.module.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html>
      <body className={cl(inter.className, s.body)}>{children}</body>
    </html>
  )
}
