import { Layout } from '@/components/Layout/Layout';
import { MobileVersionProvider } from '@/contexts/device';
import { ThemeProvider } from '@/contexts/theme';
import { StoreProvider } from '@/redux/StoreProvider';
import { Open_Sans } from 'next/font/google';
import './globals.css';

const open = Open_Sans({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='ru'>
      <body className={open.className}>
        <StoreProvider>
          <MobileVersionProvider>
            <ThemeProvider>
              <Layout>{children}</Layout>
            </ThemeProvider>
          </MobileVersionProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
